# .github/workflows/build-apk.yml

# This workflow builds a Kivy Android app using Buildozer.
# It is triggered on a push to the 'main' branch.

name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # Action to check out your project's code from the repository.
        uses: actions/checkout@v4

      - name: Set up Python
        # Action to set up Python, which is required for Kivy and Buildozer.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer dependencies
        # Install the system dependencies required by Buildozer on Ubuntu.
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            zlib1g-dev \
            libncursesw5-dev \
            libssl-dev \
            libffi-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            libjpeg-dev \
            libpng-dev \
            libopenjp2-7 \
            libhdf5-dev \
            python3-setuptools \
            libtool \
            autoconf

      - name: Install Buildozer and core dependencies
        # Install the buildozer tool, Cython, and Pillow using pip.
        run: pip install buildozer cython pillow

      - name: Create buildozer.spec file
        # This step overwrites the buildozer.spec file with a clean, correct version.
        run: |
          cat <<EOF > buildozer.spec
          [app]
          title = PyCam
          package.name = pycam
          package.domain = org.test.pycam
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,spec
          version = 0.1
          requirements = python3,kivy,pillow
          android.minapi = 21
          android.sdk = 33
          android.ndk = 25b
          android.build_tools_version = 30.0.3
          android.archs = arm64-v8a,armeabi-v7a
          android.accept_sdk_license = True
          android.abisplit = False
          android.entrypoint = org.kivy.android.PythonActivity
          android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
          android.release = False
          [buildozer]
          buildozer.dir = ./.buildozer
          EOF

      - name: Build Android APK
        # Run Buildozer to compile the app and create the APK.
        run: buildozer -v android debug

      - name: Upload APK artifact
        # This step saves the generated APK file to the GitHub Action workflow.
        uses: actions/upload-artifact@v4
        with:
          name: pycam-apk
          path: bin/*.apk
